# Mass Download of R Packages for met workflow

# adjust these variables
user = 'mkivi'
# 

first = substr(user,1,1)

if (!require('abind',lib.loc ='~/Rlibs')) install.packages('abind',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('colorspace',lib.loc='~/Rlibs')) install.packages('colorspace',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('data.table',lib.loc ='~/Rlibs')) install.packages('data.table',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('dplyr',lib.loc='~/Rlibs')) install.packages('dplyr',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('ggplot2',lib.loc='~/Rlibs')) install.packages('ggplot2',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('glue', lib.loc = paste0('/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs'))) install.packages('glue',lib=paste0('/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs'),repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('latex2exp',lib.loc='~/Rlibs')) install.packages('latex2exp',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('limSolve',lib.loc='~/Rlibs')) install.packages('limSolve',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('lubridate',lib.loc='~/Rlibs')) install.packages('lubridate',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('maps',lib.loc='~/Rlibs')) install.packages('maps',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('MASS',lib.loc='~/Rlibs')) install.packages('MASS',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('mgcv',lib.loc='~/Rlibs')) install.packages('mgcv',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('ncdf4',lib.loc ='~/Rlibs')) install.packages('ncdf4',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('parallel',lib.loc ='~/Rlibs')) install.packages('parallel',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('plyr',lib.loc ='~/Rlibs')) install.packages('plyr',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('raster',lib.loc ='~/Rlibs')) install.packages('raster',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('reshape2',lib.loc ='~/Rlibs')) install.packages('reshape2',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('rgdal',lib.loc ='~/Rlibs')) install.packages('rgdal',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('R.matlab',lib.loc ='~/Rlibs')) install.packages('R.matlab',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('sp',lib.loc='~/Rlibs')) install.packages('sp',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('stringr',lib.loc='~/Rlibs')) install.packages('stringr',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=T)
if (!require('stats',lib.loc='~/Rlibs')) install.packages('stats',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('tibble', lib.loc = paste0('/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs'))) install.packages('tibble',lib=paste0('/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs'),repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('tictoc',lib.loc='~/Rlibs')) install.packages('tictoc',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)
if (!require('utils',lib.loc='~/Rlibs')) install.packages('utils',lib='~/Rlibs',repos='http://cran.us.r-project.org',dependencies=TRUE)

Sys.setenv(LD_LIBRARY_PATH=paste0(Sys.getenv("LD_LIBRARY_PATH"), ":","/afs/crc.nd.edu/user/",first,"/",user,"/Rlibs/udunits/local/lib"))
if (!require('udunits2', lib.loc ='~/Rlibs')) install.packages('udunits2',type = 'source',repos = "http://cran.rstudio.com",lib='~/Rlibs',dependencies=TRUE, configure.args=paste0('--with-udunits2-lib=/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs/udunits/local/lib --with-udunits2-include=/afs/crc.nd.edu/user/',first,'/',user,'/Rlibs/udunits/local/include'))
dyn.load(paste0("/afs/crc.nd.edu/user/",first,"/:",user,"/Rlibs/udunits/local/lib/libudunits2.so.0"))

require(abind,lib.loc='~/Rlibs')
require(colorspace,lib.loc='~/Rlibs')
require(data.table,lib.loc='~/Rlibs')
require(dplyr,lib.loc='~/Rlibs')
require(ggplot2,lib.loc='~/Rlibs')
require(glue,lib.loc='~/Rlibs')
require(latex2exp,lib.loc='~/Rlibs')
require(limSolve,lib.loc='~/Rlibs')
require(lubridate, lib.loc='~/Rlibs')
require(maps,lib.loc='~/Rlibs')
require(MASS,lib.loc='~/Rlibs')
require(mgcv,lib.loc='~/Rlibs')
require(ncdf4,lib.loc='~/Rlibs')
require(parallel,lib.loc='~/Rlibs')
require(plyr,lib.loc='~/Rlibs')
require(raster, lib.loc='~/Rlibs')
require(reshape2,lib.loc='~/Rlibs')
require(rgdal,lib.loc='~/Rlibs')
require(R.matlab,lib.loc='~/Rlibs')
require(sp, lib.loc='~/Rlibs')
require(stringr,lib.loc='~/Rlibs')
require(stats,lib.loc='~/Rlibs')
require(tibble,lib.loc='~/Rlibs')
require(tictoc,lib.loc='~/Rlibs')
require(udunits2,lib.loc='~/Rlibs')
require(utils,lib.loc='~/Rlibs')

